// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/transfer-gateway/gateway/fns.proto

package gateway

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type WithdrawalMessage struct {
	TokenOwner           *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	WithdrawalHash       []byte         `protobuf:"bytes,2,opt,name=withdrawal_hash,json=withdrawalHash,proto3" json:"withdrawal_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WithdrawalMessage) Reset()         { *m = WithdrawalMessage{} }
func (m *WithdrawalMessage) String() string { return proto.CompactTextString(m) }
func (*WithdrawalMessage) ProtoMessage()    {}
func (*WithdrawalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fns_35a5d2cd7ff6a17a, []int{0}
}
func (m *WithdrawalMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawalMessage.Unmarshal(m, b)
}
func (m *WithdrawalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawalMessage.Marshal(b, m, deterministic)
}
func (dst *WithdrawalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawalMessage.Merge(dst, src)
}
func (m *WithdrawalMessage) XXX_Size() int {
	return xxx_messageInfo_WithdrawalMessage.Size(m)
}
func (m *WithdrawalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawalMessage proto.InternalMessageInfo

func (m *WithdrawalMessage) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *WithdrawalMessage) GetWithdrawalHash() []byte {
	if m != nil {
		return m.WithdrawalHash
	}
	return nil
}

type BatchWithdrawalFnMessage struct {
	WithdrawalMessages   []*WithdrawalMessage `protobuf:"bytes,1,rep,name=withdrawal_messages,json=withdrawalMessages" json:"withdrawal_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BatchWithdrawalFnMessage) Reset()         { *m = BatchWithdrawalFnMessage{} }
func (m *BatchWithdrawalFnMessage) String() string { return proto.CompactTextString(m) }
func (*BatchWithdrawalFnMessage) ProtoMessage()    {}
func (*BatchWithdrawalFnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fns_35a5d2cd7ff6a17a, []int{1}
}
func (m *BatchWithdrawalFnMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchWithdrawalFnMessage.Unmarshal(m, b)
}
func (m *BatchWithdrawalFnMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchWithdrawalFnMessage.Marshal(b, m, deterministic)
}
func (dst *BatchWithdrawalFnMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchWithdrawalFnMessage.Merge(dst, src)
}
func (m *BatchWithdrawalFnMessage) XXX_Size() int {
	return xxx_messageInfo_BatchWithdrawalFnMessage.Size(m)
}
func (m *BatchWithdrawalFnMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchWithdrawalFnMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BatchWithdrawalFnMessage proto.InternalMessageInfo

func (m *BatchWithdrawalFnMessage) GetWithdrawalMessages() []*WithdrawalMessage {
	if m != nil {
		return m.WithdrawalMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*WithdrawalMessage)(nil), "gateway.WithdrawalMessage")
	proto.RegisterType((*BatchWithdrawalFnMessage)(nil), "gateway.BatchWithdrawalFnMessage")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/transfer-gateway/gateway/fns.proto", fileDescriptor_fns_35a5d2cd7ff6a17a)
}

var fileDescriptor_fns_35a5d2cd7ff6a17a = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x05, 0x95, 0xac, 0x28, 0xae, 0x97, 0xd0, 0xd3, 0xd2, 0x8b, 0xeb, 0xa1, 0x89,
	0xd4, 0x93, 0x47, 0x3d, 0x88, 0x20, 0x22, 0xec, 0xc5, 0x63, 0x99, 0x76, 0xa7, 0x49, 0x69, 0x37,
	0x53, 0x32, 0x23, 0xa1, 0xff, 0x5e, 0xda, 0x6d, 0x5d, 0x51, 0xbc, 0x24, 0xe4, 0x7b, 0xbc, 0xf7,
	0xf2, 0xd4, 0x83, 0x5b, 0x88, 0xff, 0x9c, 0x9a, 0x19, 0xb5, 0x76, 0x45, 0xd4, 0x06, 0x94, 0x44,
	0x71, 0x69, 0x25, 0x42, 0xe0, 0x39, 0xc6, 0x91, 0x03, 0xc1, 0x04, 0x1b, 0x7b, 0xb8, 0xe7, 0x81,
	0xcd, 0x3a, 0x92, 0x50, 0x71, 0xba, 0x47, 0x83, 0xbb, 0x7f, 0x32, 0x1c, 0x8d, 0xb6, 0x4f, 0x2b,
	0x9b, 0x35, 0x72, 0x77, 0x76, 0xd6, 0xa1, 0x53, 0x57, 0x1f, 0x0b, 0xf1, 0x4d, 0x84, 0x04, 0xab,
	0x37, 0x64, 0x06, 0x87, 0xc5, 0xad, 0xca, 0x85, 0x96, 0x18, 0x26, 0x94, 0x02, 0x46, 0x9d, 0x95,
	0x59, 0x95, 0x8f, 0xcf, 0xcc, 0x63, 0xd3, 0x44, 0x64, 0xae, 0xd5, 0x4e, 0x7c, 0xdf, 0x6a, 0xc5,
	0x8d, 0xba, 0x4c, 0xdf, 0xfe, 0x89, 0x07, 0xf6, 0xfa, 0xa8, 0xcc, 0xaa, 0xf3, 0xfa, 0xa2, 0xc7,
	0x2f, 0xc0, 0x7e, 0xe8, 0x94, 0x7e, 0x02, 0x99, 0xf9, 0xbe, 0xed, 0x39, 0x1c, 0xfa, 0x5e, 0xd5,
	0xf5, 0x8f, 0x90, 0xb6, 0xa3, 0xac, 0xb3, 0xf2, 0xb8, 0xca, 0xc7, 0x03, 0xb3, 0x5f, 0x67, 0xfe,
	0x7c, 0xb4, 0x2e, 0xd2, 0x6f, 0xc4, 0xd3, 0x93, 0xdd, 0xb0, 0xfb, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xeb, 0x47, 0x0a, 0x03, 0x50, 0x01, 0x00, 0x00,
}
