// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/transfer-gateway/gateway/gateway.proto

package gateway

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OracleState struct {
	Timestamp             int64          `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalWithdrawalAmount *types.BigUInt `protobuf:"bytes,2,opt,name=total_withdrawal_amount,json=totalWithdrawalAmount" json:"total_withdrawal_amount,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *OracleState) Reset()         { *m = OracleState{} }
func (m *OracleState) String() string { return proto.CompactTextString(m) }
func (*OracleState) ProtoMessage()    {}
func (*OracleState) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_d91217ac4834324f, []int{0}
}
func (m *OracleState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OracleState.Unmarshal(m, b)
}
func (m *OracleState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OracleState.Marshal(b, m, deterministic)
}
func (dst *OracleState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleState.Merge(dst, src)
}
func (m *OracleState) XXX_Size() int {
	return xxx_messageInfo_OracleState.Size(m)
}
func (m *OracleState) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleState.DiscardUnknown(m)
}

var xxx_messageInfo_OracleState proto.InternalMessageInfo

func (m *OracleState) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OracleState) GetTotalWithdrawalAmount() *types.BigUInt {
	if m != nil {
		return m.TotalWithdrawalAmount
	}
	return nil
}

type Account struct {
	Owner                 *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Timestamp             int64          `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalWithdrawalAmount *types.BigUInt `protobuf:"bytes,3,opt,name=total_withdrawal_amount,json=totalWithdrawalAmount" json:"total_withdrawal_amount,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_d91217ac4834324f, []int{1}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Account) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Account) GetTotalWithdrawalAmount() *types.BigUInt {
	if m != nil {
		return m.TotalWithdrawalAmount
	}
	return nil
}

func init() {
	proto.RegisterType((*OracleState)(nil), "OracleState")
	proto.RegisterType((*Account)(nil), "Account")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/transfer-gateway/gateway/gateway.proto", fileDescriptor_gateway_d91217ac4834324f)
}

var fileDescriptor_gateway_d91217ac4834324f = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x8b, 0xff, 0xb6, 0xb7, 0x80, 0x58, 0x44, 0xa4, 0xf4, 0xd4, 0x4b, 0x13, 0xd1,
	0xb3, 0x60, 0xbc, 0x79, 0x12, 0x22, 0xe2, 0xb1, 0x4c, 0x93, 0x71, 0xbb, 0xb8, 0xbb, 0x13, 0x66,
	0xa7, 0x2c, 0xf9, 0x08, 0x7e, 0x6b, 0xc9, 0x06, 0x14, 0x05, 0x41, 0x2f, 0xf3, 0xe7, 0xf1, 0x1e,
	0xf3, 0x63, 0xd4, 0xad, 0x36, 0xb2, 0xdb, 0x6f, 0x8b, 0x86, 0x5c, 0x69, 0x89, 0x9c, 0x47, 0x89,
	0xc4, 0x6f, 0xa5, 0x30, 0xf8, 0xf0, 0x8a, 0xbc, 0xd6, 0x20, 0x18, 0xa1, 0x2f, 0x7f, 0xf4, 0xa2,
	0x63, 0x12, 0x3a, 0xbf, 0xfa, 0x25, 0xae, 0x69, 0x3d, 0xac, 0xa5, 0xf4, 0x1d, 0x86, 0xb1, 0x8e,
	0x89, 0xa5, 0x53, 0xb3, 0x47, 0x86, 0xc6, 0xe2, 0x93, 0x80, 0x60, 0x7e, 0xa1, 0x4e, 0xc4, 0x38,
	0x0c, 0x02, 0xae, 0x9b, 0x67, 0x8b, 0x6c, 0x35, 0xad, 0xbf, 0x84, 0xfc, 0x4e, 0x9d, 0x09, 0x09,
	0xd8, 0x4d, 0x34, 0xb2, 0x6b, 0x19, 0x22, 0xd8, 0x0d, 0x38, 0xda, 0x7b, 0x99, 0x4f, 0x16, 0xd9,
	0x6a, 0x76, 0x7d, 0x5c, 0xdc, 0x1b, 0xfd, 0xfc, 0xe0, 0xa5, 0x3e, 0x4d, 0xc6, 0x97, 0x4f, 0x5f,
	0x95, 0x6c, 0xcb, 0xf7, 0x4c, 0x1d, 0x55, 0x4d, 0x33, 0xcc, 0xf9, 0xa5, 0x3a, 0xa0, 0xe8, 0x91,
	0xd3, 0x9d, 0x21, 0x5b, 0xb5, 0x2d, 0x63, 0x08, 0xf5, 0x28, 0x7f, 0x67, 0x99, 0xfc, 0x83, 0x65,
	0xfa, 0x27, 0x96, 0xed, 0x61, 0xfa, 0xc0, 0xcd, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x44,
	0x40, 0xf1, 0x74, 0x01, 0x00, 0x00,
}
